/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup CustomGroup;
extern const Sifteo::AssetImage CustomImage;
extern const Sifteo::AssetImage WhiteImage;
extern const Sifteo::AssetImage gateImage;
extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
